### ISSUE TITLE
O contador de palavras em imagens não é capaz de identificar palavras em arquivos de vetor e no ambiente TikZ

### ISSUE THREAD

**Issue by LucasNtSt** [comissao-aerodesign/PyAeroCounter#4]
O contador de palavras em imagens não é capaz de identificar palavras em arquivos de vetor como .pdf e .eps que podem ser inseridos com o comando \includegraphics. Uma imagem do matlab, por exemplo, exportada em .png tem suas palavras reconhecidas pelo contador como "Word in Fiigures", já .pdf ou .eps não. Imagens no ambiente TikZ também não são reconhecidas.

**Comment by luccareinehr** [comment]
Tem alguma solução? Pra mim gráficos no tikz são contabilizados como várias palavras de uma vez

![image](https://user-images.githubusercontent.com/75084099/129974136-e8c6f25a-94e7-469d-9b31-29f18b613d17.png)

Triste, aumentou bastante no total de palavras :(

**Comment by complex-hub** [comment]
Infelizmente qualquer gráfico/imagem inserida como vetor (pdf, svg, etc) entra na contagem de palavras direto. A única alternativa que encontramos foi inserir como imagem mesmo, a qualidade fica menor mas a contagem entra no words in figures.
